services:
  - type: web
    name: voice-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    rootDir: voice-bot
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 